### ISSUE TITLE
close sound of notification

### ISSUE THREAD

**Issue by eng-sayed** [gdelataillade/alarm#162]
**when alarm start to ringing we can stop the sound by tap on the notification**

**Comment by gdelataillade** [comment]
Hi @eng-sayed 

Thanks for your interest in the plugin.

If you want to stop the alarm sound when notification is tapped, you can just call `Alarm.stop` on app launch. I won't add this to the plugin because in some cases we want the alarm to keep ringing when redirecting to ring screen.

Let me know if you have any question.
