### ISSUE TITLE
Show alarm on full screen like system alarm

### ISSUE THREAD

**Issue by sagar1garg** [gdelataillade/alarm#178]
System alarms are shown on full screen even when the screen is locked making it easy for a user to snooze or stop the alarm. 

Alarm plugin has a full screen display UI but notification on Android is the standard size. Can we make it to show on the entire screen (similar to the example UI) when screen is locked similar to system alarm?

**Comment by gdelataillade** [comment]
Hi @sagar1garg 

On Android, if you want the notification to be full screen you have to enable `androidFullScreenIntent` parameter and the screen has to be locked. I chose to not show the full screen notification when device is unlocked because it would be too intrusive for your users. Imagine you're watching a video or writing a message and you get interrupted by a full screen alarm notification... I believe a simple notification is enough don't you think?

I'm closing the issue then but feel free to ask if you have any question.
