### ISSUE TITLE
OVERLAP LOCK SCREEN LIKE A DEFAULT

### ISSUE THREAD

**Issue by singhcreations** [gdelataillade/alarm#190]
**OVERLAP LOCK SCREEN LIKE A DEFAULT?.**

NEED FEATURE OF OVERLAP LOCK SCREEN LIKE A DEFAULT ALARM APP IT OVERIIDE THE LOCKSEEN WHEN ALARM FIRED , AS ON NOW SOMETIMES ALARM SCREEN DIDNT CAME.

MAKE A FEATURE THIS AS WELL IF THE RING SCREEN TONE IS NOT PLAY WITH ANY REASON THEN THERE WILL BE A SECOUNDARY OPTION TO PLAY THE SOUND.

**Comment by gdelataillade** [comment]
Hi @singhcreations 

You can enable the `androidFullScreenIntent` parameter to show the alarm on your lock screen. It won't work if your screen is unlocked. There might be other conditions that would make the alarm now show in the lock screen but that would depend on the android device. I think there's nothing else I can do to improve consistency.

Like mentioned in the README, if your android alarm does not ring, it can be because your device rebooted or your app updated. I'll work on the reschedule of the alarms after device reboot very soon.

Any other question ?

**Comment by singhcreations** [comment]
Thanks for your explanation. But ring screen didn't appear 😕 I have to
open the lockscreen and then click on notification then it shows

**Comment by gdelataillade** [comment]
What device do you have ?

**Comment by gdelataillade** [comment]
To fix this issue, you might need to add [auto_start_flutter](https://pub.dev/packages/auto_start_flutter) permission request in your app.

**Comment by singhcreations** [comment]
Redmi note 11 pro plus using HYPER OS

**Comment by gdelataillade** [comment]
Xiaomi devices may required [auto_start_flutter](https://pub.dev/packages/auto_start_flutter) permission for this feature. Let me know if it helps.

**Comment by singhcreations** [comment]
If I enable show on lockscreen and display pop-up windows after using
AndroidIntent then ring screen came. but It might confusion what is the
role of Android intent if we get only notification then click on
notification to get the ring screen ?

**Comment by gdelataillade** [comment]
I didn't understand what you said.

You need to instruct your Xiaomi users (and perhaps users of other brands with similar restrictions) to grant the `auto_start` permission. This permission is crucial for the app to operate correctly in the background and to display full-screen ring notifications, similar to the default alarm app.

**Comment by singhcreations** [comment]
Ok, I will do that but I am saying that iIf I enable show on lockscreen and
display pop-up windows this on my mobile phone then automatically got the
ring screen on my device as well.
