### ISSUE TITLE
Necessity of storage permission?

### ISSUE THREAD

**Issue by Masum-MSNR** [gdelataillade/alarm#197]
Why it is necessary to have storage permission to set an alarm?
Is it possible to use this package without this permission?

**Comment by gdelataillade** [comment]
Hi @Masum-MSNR 

The storage permission is used because when an alarm is set, it is saved to the local storage of the device. This way, when you reopen the app, you can retrieve the alarm with all its information. Without this, your alarms would be two app sessions. Feel free to remove it and try it by yourself if you think you don't need it.

**Comment by Masum-MSNR** [comment]
Thanks, @gdelataillade.

I checked it without permission, and it works. I wasn't creating a full alarm app, I just needed it to trigger at a specific time. It works for that.

I was wondering if there's an option to add buttons to the notification. If so, that would be great.

**Comment by gdelataillade** [comment]
Hi @Masum-MSNR 

Glad to hear it works for you !

About the buttons on the notification, it's in my to do list but it's not the priority at the moment. I'll keep you updated here: #58

**Comment by Masum-MSNR** [comment]
Thanks
