### ISSUE TITLE
in Android 13 notification can't clear from alarm package

### ISSUE THREAD

**Issue by careconnect278** [gdelataillade/alarm#212]
**Alarm plugin version**
*3.1.4*

**Describe the bug**
*in Android 13 notification can't clear*

**Expected behavior**
*notification can clear.*

https://github.com/gdelataillade/alarm/assets/166753700/fba99216-233e-4afd-bedb-552af3b5c955

**Device info**
*Provide device info (Manufacturer, OS version, ...)*
*Ex: oneplus nord 2,oppo reno 6,samsung  m52
android 13

**Comment by gdelataillade** [comment]
Hi @careconnect278 

The alarm plugin uses Android’s Foreground Service to ensure the alarm can trigger at any time, even if the app is killed. However, for Android 12+ this requires making the notification non-dismissible due to new Android rules.

Foreground services must display a notification, and on Android 12 and later, these notifications cannot be dismissed by the user if the service is intended to run indefinitely. This is to ensure that the user is always aware of any ongoing processes that might affect battery life or device performance.
