### ISSUE TITLE
alarm overlay screen on the phone 

### ISSUE THREAD

**Issue by m-1226** [gdelataillade/alarm#270]
making overlay screen when the alarm ring over the apps and Lock Screen that I can customize this screen with title and body and button to stop the alarm not just stop it from notification

**Comment by gdelataillade** [comment]
Hi @m-1226,

On Android, make sure to follow the [setup steps](https://github.com/gdelataillade/alarm/blob/main/help/INSTALL-ANDROID.md) and set the `AlarmSettings.androidFullScreenIntent` to `true`.

The ring screen will show over the Lock Screen but not over other apps. This is because I believe it is too intrusive. Maybe some day I'll add it though.

Check out the example app to experiment with the alarm overlay screen.
