### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method Alarm.oneShotAt on channel dev.fluttercommunity.plus/android_alarm_manager)

### ISSUE THREAD

**Issue by Malay1121** [gdelataillade/alarm#5]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method Alarm.oneShotAt on channel dev.fluttercommunity.plus/android_alarm_manager)

**Comment by gdelataillade** [comment]
That's weird. Have you tried to run a `flutter clean` ?

**Comment by Malay1121** [comment]
Yes, I tried. DIdnt work

**Comment by yelkamel** [comment]
Thank you for bringing this issue to our attention. 

We really don't understand you error, in the package we use only "android_alarm_manager_plus" not the "android_alarm_manager". 

We apologize for any inconvenience this may have caused. 

In order to help us better understand and replicate the problem, could you please try creating a new, empty repository and see if the error persists? 

This will help us to identify and resolve the issue more quickly. 

Let us know if you have any further questions or concerns.

**Comment by Malay1121** [comment]
I tried flutter clean and again reinstalling the plugin and it worked!

**Comment by gdelataillade** [comment]
Great! I'll close the issue then.
