### ISSUE TITLE
Sometimes notifications Issue

### ISSUE THREAD

**Issue by dev-chetan** [gdelataillade/alarm#80]
Sometimes notifications are not coming if the background and screen lock.

**Comment by gdelataillade** [comment]
iOS or Android ?

**Comment by dev-chetan** [comment]
Both Platform.

**Comment by gdelataillade** [comment]
I published earlier version `1.2.2` where I upgrade `flutter_local_notification`, maybe it will fix your issue.

If not, please make sure you followed the instructions in the README.

Also try to take a look at the instructions steps of the [`flutter_local_notification`](https://pub.dev/packages/flutter_local_notifications) package.

Let me know if it helps. Otherwise, I'll review my code.

**Comment by gdelataillade** [comment]
In debug mode, watch the plugin's logs and make sure the notification are scheduled for the right GMT DateTime.

**Comment by dev-chetan** [comment]
Hello, @gdelataillade

I'm updating to the new version 1.2.2 but not arrived, the issue is already there.
and enableNotificationOnKill: true this flag set true but did not arrive a kill notification

**Comment by gdelataillade** [comment]
Hi @dev-chetan 

Looks like you have an issue with notifications, that's really weird. Have you tried to uninstall/reinstall your app and made sure you gave notification permission ? You can also change the permission in your device Settings.

**Comment by dev-chetan** [comment]
if I have a set alarm after 5 min so works fine with sound and notification than set more time sound done but not get notification.

**Comment by gdelataillade** [comment]
Are you testing with the example app or with you own app ?
